spring:
  application:
    name: User-service-v2.6.5
  cloud:
    inetutils:
      preferred-networks:
        - 10.0

server:
  port: 33001

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.0.80.8:10002/eureka/
  instance:	
    prefer-ip-address: true
    instance-id=
      
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  #file: userservice.log
  file: /var/kido/logs/userservice.log
